#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOF
CREATE USER $POSTGRES_WRITE_USER WITH PASSWORD '$POSTGRES_WRITE_PASSWORD';
CREATE USER $POSTGRES_READ_USER WITH PASSWORD '$POSTGRES_READ_PASSWORD';

-- Write user permissions
GRANT CONNECT ON DATABASE $POSTGRES_DB TO $POSTGRES_WRITE_USER;
GRANT USAGE, CREATE ON SCHEMA public TO $POSTGRES_WRITE_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO $POSTGRES_WRITE_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO $POSTGRES_WRITE_USER;

-- Read user permissions (existing tables)
GRANT CONNECT ON DATABASE $POSTGRES_DB TO $POSTGRES_READ_USER;
GRANT USAGE ON SCHEMA public TO $POSTGRES_READ_USER;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO $POSTGRES_READ_USER;

-- Grant default privileges for tables created BY the write user
ALTER DEFAULT PRIVILEGES FOR ROLE $POSTGRES_WRITE_USER IN SCHEMA public
GRANT SELECT ON TABLES TO $POSTGRES_READ_USER;

-- Also grant on sequences (for auto-increment columns)
ALTER DEFAULT PRIVILEGES FOR ROLE $POSTGRES_WRITE_USER IN SCHEMA public
GRANT USAGE ON SEQUENCES TO $POSTGRES_READ_USER;
EOF

echo "===================================================="
echo "Generated database users:"
echo "$POSTGRES_WRITE_USER : $POSTGRES_WRITE_PASSWORD"
echo "$POSTGRES_READ_USER : $POSTGRES_READ_PASSWORD"
echo "===================================================="
